version: "3.8"
services:
  backend:
    build:
      context: ./Backend Ticket Nepal/Backend
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
    ports:
      - "8080:8080"
    depends_on: []

  frontend:
    build:
      context: ./Frontend Ticket Nepal/TicketNepal
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend 